// Кристаллы конфигуратора ПЛИС askoRV32: выводы корпусов (из Gowin IDE) и свойства семейств.
// Файл создан sw/socgen/mkdevices.py - не редактируйте вручную. Его читают страница конфигуратора
// (<script>) и генератор socgen.py (JSON после GWSOC_DEVICES).
window.GWSOC_DEVICES = {
"GW1NR-LV9QN88PC6/I5": {"part": "GW1NR-LV9QN88PC6/I5", "deviceId": "gw1nr9c-004", "package": "QFN88P", "pkgType": "QUAD", "perSide": 22, "title": "GW1NR-LV9QN88P", "family": "GW1NR-9C", "idcode": "0x1100481B", "series": "GW1NR-9", "version": "C", "pllDevice": "GW1NR-9C", "pll": {"inMin": 3, "inMax": 400, "pfdMin": 3, "pfdMax": 400, "vcoMin": 400, "vcoMax": 1200, "outMin": 3.125, "outMax": 600}, "vcc": "1.2", "embeddedFlash": true, "mergetool": true, "cfgRegion": 524288, "cfgUser": 1048576, "resources": {"lut": 8640, "reg": 6480, "bsram": 26, "dsp": 10, "io": 71, "pll": 2}, "dualPurpose": {"MSPI": [["MCLK", "MCS_N", "MO", "MI"], "--mspi_as_gpio"]}, "apicula": {"family": "GW1N-9C", "jtag": false}, "source": "Gowin IDE, data/device/GW1NR-9C/QFN88P.json", "pins": [
  {"n": 1, "name": "VCC", "type": "pwr"},
  {"n": 2, "name": "VSS", "type": "gnd"},
  {"n": 3, "name": "IOT2A", "type": "io", "bank": 3, "diff": "P", "pair": "IOT2B"},
  {"n": 4, "name": "IOL5A", "type": "io", "bank": 3, "cfg": "JTAGSEL_N/LPLL_T_IN", "diff": "P", "pair": "IOL5B"},
  {"n": 5, "name": "IOL11A", "type": "io", "bank": 3, "cfg": "TMS", "diff": "P", "pair": "IOL11B", "lvds": true},
  {"n": 6, "name": "IOL11B", "type": "io", "bank": 3, "cfg": "TCK", "diff": "N", "pair": "IOL11A", "lvds": true},
  {"n": 7, "name": "IOL12B", "type": "io", "bank": 3, "cfg": "TDI", "diff": "N", "pair": "IOL12A"},
  {"n": 8, "name": "IOL13A", "type": "io", "bank": 3, "cfg": "TDO", "diff": "P", "pair": "IOL13B", "lvds": true},
  {"n": 9, "name": "IOL13B", "type": "io", "bank": 3, "cfg": "RECONFIG_N", "diff": "N", "pair": "IOL13A", "lvds": true},
  {"n": 10, "name": "IOL15A", "type": "io", "bank": 3, "cfg": "GCLKT_6", "diff": "P", "pair": "IOL15B", "lvds": true},
  {"n": 11, "name": "IOL16B", "type": "io", "bank": 3, "diff": "N", "pair": "IOL16A"},
  {"n": 12, "name": "VCCIO3", "type": "pwr"},
  {"n": 13, "name": "IOL21B", "type": "io", "bank": 3, "diff": "N", "pair": "IOL21A"},
  {"n": 14, "name": "IOL22B", "type": "io", "bank": 3, "diff": "N", "pair": "IOL22A", "lvds": true},
  {"n": 15, "name": "IOL25B", "type": "io", "bank": 3, "diff": "N", "pair": "IOL25A"},
  {"n": 16, "name": "IOL26B", "type": "io", "bank": 3, "diff": "N", "pair": "IOL26A", "lvds": true},
  {"n": 17, "name": "IOB2A", "type": "io", "bank": 2, "diff": "P", "pair": "IOB2B", "lvds": true},
  {"n": 18, "name": "IOB2B", "type": "io", "bank": 2, "diff": "N", "pair": "IOB2A", "lvds": true},
  {"n": 19, "name": "IOB4A", "type": "io", "bank": 2, "diff": "P", "pair": "IOB4B", "lvds": true},
  {"n": 20, "name": "IOB4B", "type": "io", "bank": 2, "diff": "N", "pair": "IOB4A", "lvds": true},
  {"n": 21, "name": "VSS", "type": "gnd"},
  {"n": 22, "name": "VCC", "type": "pwr"},
  {"n": 23, "name": "VCCIO2", "type": "pwr"},
  {"n": 24, "name": "VSS", "type": "gnd"},
  {"n": 25, "name": "IOB8A", "type": "io", "bank": 2, "diff": "P", "pair": "IOB8B", "lvds": true},
  {"n": 26, "name": "IOB8B", "type": "io", "bank": 2, "diff": "N", "pair": "IOB8A", "lvds": true},
  {"n": 27, "name": "IOB11A", "type": "io", "bank": 2, "diff": "P", "pair": "IOB11B", "lvds": true},
  {"n": 28, "name": "IOB11B", "type": "io", "bank": 2, "diff": "N", "pair": "IOB11A", "lvds": true},
  {"n": 29, "name": "IOB13A", "type": "io", "bank": 2, "diff": "P", "pair": "IOB13B", "lvds": true},
  {"n": 30, "name": "IOB13B", "type": "io", "bank": 2, "diff": "N", "pair": "IOB13A", "lvds": true},
  {"n": 31, "name": "IOB15A", "type": "io", "bank": 2, "diff": "P", "pair": "IOB15B", "lvds": true},
  {"n": 32, "name": "IOB15B", "type": "io", "bank": 2, "diff": "N", "pair": "IOB15A", "lvds": true},
  {"n": 33, "name": "IOB23A", "type": "io", "bank": 2, "diff": "P", "pair": "IOB23B", "lvds": true},
  {"n": 34, "name": "IOB23B", "type": "io", "bank": 2, "diff": "N", "pair": "IOB23A", "lvds": true},
  {"n": 35, "name": "IOB29A", "type": "io", "bank": 2, "cfg": "GCLKT_4", "diff": "P", "pair": "IOB29B", "lvds": true},
  {"n": 36, "name": "IOB29B", "type": "io", "bank": 2, "cfg": "GCLKC_4", "diff": "N", "pair": "IOB29A", "lvds": true},
  {"n": 37, "name": "IOB31A", "type": "io", "bank": 2, "diff": "P", "pair": "IOB31B", "lvds": true},
  {"n": 38, "name": "IOB31B", "type": "io", "bank": 2, "diff": "N", "pair": "IOB31A", "lvds": true},
  {"n": 39, "name": "IOB33A", "type": "io", "bank": 2, "diff": "P", "pair": "IOB33B", "lvds": true},
  {"n": 40, "name": "IOB33B", "type": "io", "bank": 2, "diff": "N", "pair": "IOB33A", "lvds": true},
  {"n": 41, "name": "IOB41A", "type": "io", "bank": 2, "diff": "P", "pair": "IOB41B", "lvds": true},
  {"n": 42, "name": "IOB41B", "type": "io", "bank": 2, "diff": "N", "pair": "IOB41A", "lvds": true},
  {"n": 43, "name": "VSS", "type": "gnd"},
  {"n": 44, "name": "VCCIO2", "type": "pwr"},
  {"n": 45, "name": "VCC", "type": "pwr"},
  {"n": 46, "name": "VSS", "type": "gnd"},
  {"n": 47, "name": "IOB43B", "type": "io", "bank": 2, "diff": "N", "pair": "IOB43A", "lvds": true},
  {"n": 48, "name": "IOR24B", "type": "io", "bank": 1, "diff": "N", "pair": "IOR24A", "lvds": true},
  {"n": 49, "name": "IOR24A", "type": "io", "bank": 1, "diff": "P", "pair": "IOR24B", "lvds": true},
  {"n": 50, "name": "IOR22B", "type": "io", "bank": 1, "diff": "N", "pair": "IOR22A", "lvds": true},
  {"n": 51, "name": "IOR17B", "type": "io", "bank": 1, "cfg": "GCLKC_3", "diff": "N", "pair": "IOR17A", "lvds": true},
  {"n": 52, "name": "IOR17A", "type": "io", "bank": 1, "cfg": "GCLKT_3", "diff": "P", "pair": "IOR17B", "lvds": true},
  {"n": 53, "name": "IOR15B", "type": "io", "bank": 1, "cfg": "DOUT/WE_N", "diff": "N", "pair": "IOR15A", "lvds": true},
  {"n": 54, "name": "IOR15A", "type": "io", "bank": 1, "cfg": "DIN/CLKHOLD_N", "diff": "P", "pair": "IOR15B", "lvds": true},
  {"n": 55, "name": "IOR14B", "type": "io", "bank": 1, "cfg": "SSPI_CS_N/D0", "diff": "N", "pair": "IOR14A"},
  {"n": 56, "name": "IOR14A", "type": "io", "bank": 1, "cfg": "SO/D1", "diff": "P", "pair": "IOR14B"},
  {"n": 57, "name": "IOR13A", "type": "io", "bank": 1, "cfg": "FASTRD_N/D3", "diff": "P", "pair": "IOR13B", "lvds": true},
  {"n": 58, "name": "VCCIO1", "type": "pwr"},
  {"n": 59, "name": "IOR12B", "type": "io", "bank": 1, "cfg": "MCLK/D4", "diff": "N", "pair": "IOR12A"},
  {"n": 60, "name": "IOR12A", "type": "io", "bank": 1, "cfg": "MCS_N/D5", "diff": "P", "pair": "IOR12B"},
  {"n": 61, "name": "IOR11B", "type": "io", "bank": 1, "cfg": "MO/D6", "diff": "N", "pair": "IOR11A", "lvds": true},
  {"n": 62, "name": "IOR11A", "type": "io", "bank": 1, "cfg": "MI/D7", "diff": "P", "pair": "IOR11B", "lvds": true},
  {"n": 63, "name": "IOR5A", "type": "io", "bank": 1, "cfg": "RPLL_T_IN", "diff": "P", "pair": "IOR5B"},
  {"n": 64, "name": "VCCIO0/VCCX", "type": "pwr"},
  {"n": 65, "name": "VSS", "type": "gnd"},
  {"n": 66, "name": "VCC", "type": "pwr"},
  {"n": 67, "name": "VCCIO0/VCCX", "type": "pwr"},
  {"n": 68, "name": "IOT42B", "type": "io", "bank": 1, "diff": "N", "pair": "IOT42A"},
  {"n": 69, "name": "IOT42A", "type": "io", "bank": 1, "diff": "P", "pair": "IOT42B"},
  {"n": 70, "name": "IOT41B", "type": "io", "bank": 1, "diff": "N", "pair": "IOT41A"},
  {"n": 71, "name": "IOT41A", "type": "io", "bank": 1, "diff": "P", "pair": "IOT41B"},
  {"n": 72, "name": "IOT39B", "type": "io", "bank": 1, "diff": "N", "pair": "IOT39A"},
  {"n": 73, "name": "IOT39A", "type": "io", "bank": 1, "diff": "P", "pair": "IOT39B"},
  {"n": 74, "name": "IOT38B", "type": "io", "bank": 1, "diff": "N", "pair": "IOT38A"},
  {"n": 75, "name": "IOT38A", "type": "io", "bank": 1, "diff": "P", "pair": "IOT38B"},
  {"n": 76, "name": "IOT37B", "type": "io", "bank": 1, "diff": "N", "pair": "IOT37A"},
  {"n": 77, "name": "IOT37A", "type": "io", "bank": 1, "diff": "P", "pair": "IOT37B"},
  {"n": 78, "name": "VCCIO0/VCCX", "type": "pwr"},
  {"n": 79, "name": "IOT12B", "type": "io", "bank": 3, "diff": "N", "pair": "IOT12A"},
  {"n": 80, "name": "IOT12A", "type": "io", "bank": 3, "diff": "P", "pair": "IOT12B"},
  {"n": 81, "name": "IOT11B", "type": "io", "bank": 3, "diff": "N", "pair": "IOT11A"},
  {"n": 82, "name": "IOT11A", "type": "io", "bank": 3, "diff": "P", "pair": "IOT11B"},
  {"n": 83, "name": "IOT10B", "type": "io", "bank": 3, "diff": "N", "pair": "IOT10A"},
  {"n": 84, "name": "IOT10A", "type": "io", "bank": 3, "diff": "P", "pair": "IOT10B"},
  {"n": 85, "name": "IOT8B", "type": "io", "bank": 3, "diff": "N", "pair": "IOT8A"},
  {"n": 86, "name": "IOT8A", "type": "io", "bank": 3, "diff": "P", "pair": "IOT8B"},
  {"n": 87, "name": "IOT6B", "type": "io", "bank": 3, "cfg": "MODE1", "diff": "N", "pair": "IOT6A"},
  {"n": 88, "name": "IOT5A", "type": "io", "bank": 3, "cfg": "MODE0", "diff": "P", "pair": "IOT5B"}
]},
"GW2A-LV18PG256C8/I7": {"part": "GW2A-LV18PG256C8/I7", "deviceId": "gw2a18c-011", "package": "PBGA256", "pkgType": "ARRAY", "rows": ["A", "B", "C", "D", "E", "F", "G", "H", "J", "K", "L", "M", "N", "P", "R", "T"], "cols": 16, "title": "GW2A-LV18PG256", "family": "GW2A-18C", "idcode": "0x0000081B", "series": "GW2A-18", "version": "C", "pllDevice": "GW2A-18C", "pll": {"inMin": 3, "inMax": 500, "pfdMin": 3, "pfdMax": 500, "vcoMin": 500, "vcoMax": 1250, "outMin": 3.90625, "outMax": 625}, "vcc": "1.0", "embeddedFlash": false, "mergetool": true, "cfgRegion": 1048576, "cfgUser": 1048576, "resources": {"lut": 20736, "reg": 15552, "bsram": 46, "dsp": 24, "io": 207, "pll": 4}, "dualPurpose": {"MSPI": [["MCLK", "MCS_N", "MO", "MI"], "--mspi_as_gpio"], "SSPI": [["SCLK", "SSPI_CS_N", "SI", "SO"], "--sspi_as_gpio"], "READY": [["READY"], "--ready_as_gpio"], "DONE": [["DONE"], "--done_as_gpio"], "RECONFIG_N": [["RECONFIG_N"], "--reconfign_as_gpio"]}, "apicula": {"family": "GW2A-18C", "jtag": true}, "source": "Gowin IDE, data/device/GW2A-18C/PBGA256.json", "pins": [
  {"n": "A1", "name": "VCC", "type": "pwr"},
  {"n": "A2", "name": "IOB13B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB13A"},
  {"n": "A3", "name": "IOB4A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB4B", "lvds": true},
  {"n": "A4", "name": "IOB2A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB2B", "lvds": true},
  {"n": "A5", "name": "IOB7A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB7B"},
  {"n": "A6", "name": "IOR26B", "type": "io", "bank": 2, "cfg": "TDI", "diff": "N", "pair": "IOR26A", "lvds": true},
  {"n": "A7", "name": "IOR26A", "type": "io", "bank": 2, "cfg": "TCK", "diff": "P", "pair": "IOR26B", "lvds": true},
  {"n": "A8", "name": "IOL29B", "type": "io", "bank": 6, "cfg": "GCLKC_6", "diff": "N", "pair": "IOL29A", "lvds": true},
  {"n": "A9", "name": "IOL27A", "type": "io", "bank": 7, "cfg": "GCLKT_7", "diff": "P", "pair": "IOL27B"},
  {"n": "A10", "name": "IOL33B", "type": "io", "bank": 6, "diff": "N", "pair": "IOL33A", "lvds": true},
  {"n": "A11", "name": "IOL15A", "type": "io", "bank": 7, "diff": "P", "pair": "IOL15B", "lvds": true},
  {"n": "A12", "name": "IOL13B", "type": "io", "bank": 7, "diff": "N", "pair": "IOL13A", "lvds": true},
  {"n": "A13", "name": "IOR32A", "type": "io", "bank": 3, "cfg": "READY", "diff": "P", "pair": "IOR32B"},
  {"n": "A14", "name": "IOL8B", "type": "io", "bank": 7, "cfg": "LPLL1_C_FB", "diff": "N", "pair": "IOL8A", "lvds": true},
  {"n": "A15", "name": "IOL2B", "type": "io", "bank": 7, "diff": "N", "pair": "IOL2A", "lvds": true},
  {"n": "A16", "name": "VCC", "type": "pwr"},
  {"n": "B1", "name": "IOB8A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB8B", "lvds": true},
  {"n": "B2", "name": "VSS", "type": "gnd"},
  {"n": "B3", "name": "IOB13A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB13B"},
  {"n": "B4", "name": "IOB4B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB4A", "lvds": true},
  {"n": "B5", "name": "IOL47B", "type": "io", "bank": 6, "cfg": "LPLL2_C_FB", "diff": "N", "pair": "IOL47A", "lvds": true},
  {"n": "B6", "name": "IOB7B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB7A"},
  {"n": "B7", "name": "IOL40A", "type": "io", "bank": 6, "diff": "P", "pair": "IOL40B", "lvds": true},
  {"n": "B8", "name": "IOR25B", "type": "io", "bank": 2, "cfg": "TMS", "diff": "N", "pair": "IOR25A"},
  {"n": "B9", "name": "IOL33A", "type": "io", "bank": 6, "diff": "P", "pair": "IOL33B", "lvds": true},
  {"n": "B10", "name": "IOR31B", "type": "io", "bank": 3, "cfg": "RECONFIG_N", "diff": "N", "pair": "IOR31A", "lvds": true},
  {"n": "B11", "name": "IOL13A", "type": "io", "bank": 7, "diff": "P", "pair": "IOL13B", "lvds": true},
  {"n": "B12", "name": "IOL7B", "type": "io", "bank": 7, "cfg": "LPLL1_C_IN", "diff": "N", "pair": "IOL7A"},
  {"n": "B13", "name": "IOL8A", "type": "io", "bank": 7, "cfg": "LPLL1_T_FB", "diff": "P", "pair": "IOL8B", "lvds": true},
  {"n": "B14", "name": "IOL2A", "type": "io", "bank": 7, "diff": "P", "pair": "IOL2B", "lvds": true},
  {"n": "B15", "name": "VSS", "type": "gnd"},
  {"n": "B16", "name": "IOR30B", "type": "io", "bank": 3, "cfg": "MODE1", "diff": "N", "pair": "IOR30A"},
  {"n": "C1", "name": "IOB14A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB14B", "lvds": true},
  {"n": "C2", "name": "IOB8B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB8A", "lvds": true},
  {"n": "C3", "name": "VSS", "type": "gnd"},
  {"n": "C4", "name": "IOL47A", "type": "io", "bank": 6, "cfg": "LPLL2_T_FB", "diff": "P", "pair": "IOL47B", "lvds": true},
  {"n": "C5", "name": "IOB2B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB2A", "lvds": true},
  {"n": "C6", "name": "IOR25A", "type": "io", "bank": 2, "cfg": "TDO", "diff": "P", "pair": "IOR25B"},
  {"n": "C7", "name": "IOL40B", "type": "io", "bank": 6, "diff": "N", "pair": "IOL40A", "lvds": true},
  {"n": "C8", "name": "IOL29A", "type": "io", "bank": 6, "cfg": "GCLKT_6", "diff": "P", "pair": "IOL29B", "lvds": true},
  {"n": "C9", "name": "IOL27B", "type": "io", "bank": 7, "cfg": "GCLKC_7", "diff": "N", "pair": "IOL27A"},
  {"n": "C10", "name": "IOR39A", "type": "io", "bank": 3, "cfg": "SCLK", "diff": "P", "pair": "IOR39B"},
  {"n": "C11", "name": "IOL15B", "type": "io", "bank": 7, "diff": "N", "pair": "IOL15A", "lvds": true},
  {"n": "C12", "name": "IOL7A", "type": "io", "bank": 7, "cfg": "LPLL1_T_IN", "diff": "P", "pair": "IOL7B"},
  {"n": "C13", "name": "IOR32B", "type": "io", "bank": 3, "cfg": "DONE", "diff": "N", "pair": "IOR32A"},
  {"n": "C14", "name": "VSS", "type": "gnd"},
  {"n": "C15", "name": "IOR31A", "type": "io", "bank": 3, "cfg": "MODE2", "diff": "P", "pair": "IOR31B", "lvds": true},
  {"n": "C16", "name": "IOT5A", "type": "io", "bank": 0, "diff": "P", "pair": "IOT5B"},
  {"n": "D1", "name": "IOB9B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB9A"},
  {"n": "D2", "name": "IOB14B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB14A", "lvds": true},
  {"n": "D3", "name": "IOB9A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB9B"},
  {"n": "D4", "name": "VSS", "type": "gnd"},
  {"n": "D5", "name": "VCCIO6", "type": "pwr"},
  {"n": "D6", "name": "IOB3A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB3B"},
  {"n": "D7", "name": "IOL53B", "type": "io", "bank": 6, "diff": "N", "pair": "IOL53A", "lvds": true},
  {"n": "D8", "name": "IOL38A", "type": "io", "bank": 6, "diff": "P", "pair": "IOL38B", "lvds": true},
  {"n": "D9", "name": "IOL35B", "type": "io", "bank": 6, "diff": "N", "pair": "IOL35A", "lvds": true},
  {"n": "D10", "name": "IOL17A", "type": "io", "bank": 7, "diff": "P", "pair": "IOL17B", "lvds": true},
  {"n": "D11", "name": "IOL22A", "type": "io", "bank": 7, "diff": "P", "pair": "IOL22B", "lvds": true},
  {"n": "D12", "name": "VCCIO7", "type": "pwr"},
  {"n": "D13", "name": "VSS", "type": "gnd"},
  {"n": "D14", "name": "IOT44A", "type": "io", "bank": 1, "diff": "P", "pair": "IOT44B", "lvds": true},
  {"n": "D15", "name": "IOT5B", "type": "io", "bank": 0, "diff": "N", "pair": "IOT5A"},
  {"n": "D16", "name": "IOT4A", "type": "io", "bank": 0, "diff": "P", "pair": "IOT4B", "lvds": true},
  {"n": "E1", "name": "IOB16A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB16B", "lvds": true},
  {"n": "E2", "name": "IOB12A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB12B", "lvds": true},
  {"n": "E3", "name": "IOB12B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB12A", "lvds": true},
  {"n": "E4", "name": "VCCIO5", "type": "pwr"},
  {"n": "E5", "name": "VSS", "type": "gnd"},
  {"n": "E6", "name": "IOL53A", "type": "io", "bank": 6, "diff": "P", "pair": "IOL53B", "lvds": true},
  {"n": "E7", "name": "IOB3B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB3A"},
  {"n": "E8", "name": "IOL45B", "type": "io", "bank": 6, "cfg": "LPLL2_C_IN", "diff": "N", "pair": "IOL45A"},
  {"n": "E9", "name": "IOL38B", "type": "io", "bank": 6, "diff": "N", "pair": "IOL38A", "lvds": true},
  {"n": "E10", "name": "IOL17B", "type": "io", "bank": 7, "diff": "N", "pair": "IOL17A", "lvds": true},
  {"n": "E11", "name": "IOL31B", "type": "io", "bank": 6, "diff": "N", "pair": "IOL31A", "lvds": true},
  {"n": "E12", "name": "VSS", "type": "gnd"},
  {"n": "E13", "name": "VCCIO0", "type": "pwr"},
  {"n": "E14", "name": "IOT4B", "type": "io", "bank": 0, "diff": "N", "pair": "IOT4A", "lvds": true},
  {"n": "E15", "name": "IOT44B", "type": "io", "bank": 1, "diff": "N", "pair": "IOT44A", "lvds": true},
  {"n": "E16", "name": "IOT6A", "type": "io", "bank": 0, "diff": "P", "pair": "IOT6B", "lvds": true},
  {"n": "F1", "name": "IOB19B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB19A"},
  {"n": "F2", "name": "IOB16B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB16A", "lvds": true},
  {"n": "F3", "name": "IOB19A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB19B"},
  {"n": "F4", "name": "IOB18A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB18B", "lvds": true},
  {"n": "F5", "name": "IOB22A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB22B", "lvds": true},
  {"n": "F6", "name": "VSS", "type": "gnd"},
  {"n": "F7", "name": "IOL45A", "type": "io", "bank": 6, "cfg": "LPLL2_T_IN", "diff": "P", "pair": "IOL45B"},
  {"n": "F8", "name": "IOL35A", "type": "io", "bank": 6, "diff": "P", "pair": "IOL35B", "lvds": true},
  {"n": "F9", "name": "IOL31A", "type": "io", "bank": 6, "diff": "P", "pair": "IOL31B", "lvds": true},
  {"n": "F10", "name": "IOL11A", "type": "io", "bank": 7, "diff": "P", "pair": "IOL11B", "lvds": true},
  {"n": "F11", "name": "VSS", "type": "gnd"},
  {"n": "F12", "name": "IOT12A", "type": "io", "bank": 0, "diff": "P", "pair": "IOT12B", "lvds": true},
  {"n": "F13", "name": "IOT8A", "type": "io", "bank": 0, "diff": "P", "pair": "IOT8B", "lvds": true},
  {"n": "F14", "name": "IOT9A", "type": "io", "bank": 0, "diff": "P", "pair": "IOT9B"},
  {"n": "F15", "name": "IOT6B", "type": "io", "bank": 0, "diff": "N", "pair": "IOT6A", "lvds": true},
  {"n": "F16", "name": "IOT9B", "type": "io", "bank": 0, "diff": "N", "pair": "IOT9A"},
  {"n": "G1", "name": "IOB24A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB24B", "lvds": true},
  {"n": "G2", "name": "IOB21A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB21B"},
  {"n": "G3", "name": "IOB21B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB21A"},
  {"n": "G4", "name": "IOB20B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB20A", "lvds": true},
  {"n": "G5", "name": "IOB20A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB20B", "lvds": true},
  {"n": "G6", "name": "IOB18B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB18A", "lvds": true},
  {"n": "G7", "name": "VCC", "type": "pwr"},
  {"n": "G8", "name": "VCCX", "type": "pwr"},
  {"n": "G9", "name": "VCCIO7", "type": "pwr"},
  {"n": "G10", "name": "VCCPLLL", "type": "pwr"},
  {"n": "G11", "name": "IOT14A", "type": "io", "bank": 0, "diff": "P", "pair": "IOT14B", "lvds": true},
  {"n": "G12", "name": "IOT8B", "type": "io", "bank": 0, "diff": "N", "pair": "IOT8A", "lvds": true},
  {"n": "G13", "name": "IOT12B", "type": "io", "bank": 0, "diff": "N", "pair": "IOT12A", "lvds": true},
  {"n": "G14", "name": "IOT13B", "type": "io", "bank": 0, "diff": "N", "pair": "IOT13A"},
  {"n": "G15", "name": "IOT13A", "type": "io", "bank": 0, "diff": "P", "pair": "IOT13B"},
  {"n": "G16", "name": "IOT16A", "type": "io", "bank": 0, "diff": "P", "pair": "IOT16B", "lvds": true},
  {"n": "H1", "name": "IOB32B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB32A", "lvds": true},
  {"n": "H2", "name": "IOB24B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB24A", "lvds": true},
  {"n": "H3", "name": "IOB32A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB32B", "lvds": true},
  {"n": "H4", "name": "IOB26A", "type": "io", "bank": 5, "diff": "P", "pair": "IOB26B", "lvds": true},
  {"n": "H5", "name": "IOB35A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB35B"},
  {"n": "H6", "name": "IOB22B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB22A", "lvds": true},
  {"n": "H7", "name": "VCCIO5", "type": "pwr"},
  {"n": "H8", "name": "VSS", "type": "gnd"},
  {"n": "H9", "name": "VSS", "type": "gnd"},
  {"n": "H10", "name": "VCCIO0", "type": "pwr"},
  {"n": "H11", "name": "IOT27A", "type": "io", "bank": 0, "cfg": "GCLKT_0", "diff": "P", "pair": "IOT27B"},
  {"n": "H12", "name": "IOT14B", "type": "io", "bank": 0, "diff": "N", "pair": "IOT14A", "lvds": true},
  {"n": "H13", "name": "IOT18A", "type": "io", "bank": 0, "diff": "P", "pair": "IOT18B", "lvds": true},
  {"n": "H14", "name": "IOT20A", "type": "io", "bank": 0, "diff": "P", "pair": "IOT20B", "lvds": true},
  {"n": "H15", "name": "IOT16B", "type": "io", "bank": 0, "diff": "N", "pair": "IOT16A", "lvds": true},
  {"n": "H16", "name": "IOT20B", "type": "io", "bank": 0, "diff": "N", "pair": "IOT20A", "lvds": true},
  {"n": "J1", "name": "IOB27A", "type": "io", "bank": 5, "cfg": "GCLKT_5", "diff": "P", "pair": "IOB27B"},
  {"n": "J2", "name": "IOB34A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB34B", "lvds": true},
  {"n": "J3", "name": "IOB27B", "type": "io", "bank": 5, "cfg": "GCLKC_5", "diff": "N", "pair": "IOB27A"},
  {"n": "J4", "name": "IOB35B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB35A"},
  {"n": "J5", "name": "IOB37A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB37B"},
  {"n": "J6", "name": "IOB26B", "type": "io", "bank": 5, "diff": "N", "pair": "IOB26A", "lvds": true},
  {"n": "J7", "name": "VCCIO4", "type": "pwr"},
  {"n": "J8", "name": "VSS", "type": "gnd"},
  {"n": "J9", "name": "VSS", "type": "gnd"},
  {"n": "J10", "name": "VCCIO1", "type": "pwr"},
  {"n": "J11", "name": "IOT32A", "type": "io", "bank": 1, "diff": "P", "pair": "IOT32B", "lvds": true},
  {"n": "J12", "name": "IOT18B", "type": "io", "bank": 0, "diff": "N", "pair": "IOT18A", "lvds": true},
  {"n": "J13", "name": "IOT27B", "type": "io", "bank": 0, "cfg": "GCLKC_0", "diff": "N", "pair": "IOT27A"},
  {"n": "J14", "name": "IOT22B", "type": "io", "bank": 0, "diff": "N", "pair": "IOT22A", "lvds": true},
  {"n": "J15", "name": "IOT24A", "type": "io", "bank": 0, "diff": "P", "pair": "IOT24B", "lvds": true},
  {"n": "J16", "name": "IOT22A", "type": "io", "bank": 0, "diff": "P", "pair": "IOT22B", "lvds": true},
  {"n": "K1", "name": "IOB34B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB34A", "lvds": true},
  {"n": "K2", "name": "IOB36B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB36A", "lvds": true},
  {"n": "K3", "name": "IOB36A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB36B", "lvds": true},
  {"n": "K4", "name": "IOB39A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB39B"},
  {"n": "K5", "name": "IOB40A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB40B", "lvds": true},
  {"n": "K6", "name": "IOB37B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB37A"},
  {"n": "K7", "name": "VCCPLLR", "type": "pwr"},
  {"n": "K8", "name": "VCCIO3", "type": "pwr"},
  {"n": "K9", "name": "VCCX", "type": "pwr"},
  {"n": "K10", "name": "VCC", "type": "pwr"},
  {"n": "K11", "name": "IOT38A", "type": "io", "bank": 1, "diff": "P", "pair": "IOT38B", "lvds": true},
  {"n": "K12", "name": "IOT36B", "type": "io", "bank": 1, "diff": "N", "pair": "IOT36A", "lvds": true},
  {"n": "K13", "name": "IOT36A", "type": "io", "bank": 1, "diff": "P", "pair": "IOT36B", "lvds": true},
  {"n": "K14", "name": "IOT30A", "type": "io", "bank": 1, "cfg": "GCLKT_1", "diff": "P", "pair": "IOT30B", "lvds": true},
  {"n": "K15", "name": "IOT30B", "type": "io", "bank": 1, "cfg": "GCLKC_1", "diff": "N", "pair": "IOT30A", "lvds": true},
  {"n": "K16", "name": "IOT24B", "type": "io", "bank": 0, "diff": "N", "pair": "IOT24A", "lvds": true},
  {"n": "L1", "name": "IOB38A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB38B", "lvds": true},
  {"n": "L2", "name": "IOB30A", "type": "io", "bank": 4, "cfg": "GCLKT_4", "diff": "P", "pair": "IOB30B", "lvds": true},
  {"n": "L3", "name": "IOB38B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB38A", "lvds": true},
  {"n": "L4", "name": "IOB40B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB40A", "lvds": true},
  {"n": "L5", "name": "IOB39B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB39A"},
  {"n": "L6", "name": "VSS", "type": "gnd"},
  {"n": "L7", "name": "EXTR", "type": "gnd"},
  {"n": "L8", "name": "IOR44B", "type": "io", "bank": 3, "diff": "N", "pair": "IOR44A", "lvds": true},
  {"n": "L9", "name": "IOR40B", "type": "io", "bank": 3, "diff": "N", "pair": "IOR40A", "lvds": true},
  {"n": "L10", "name": "IOR34B", "type": "io", "bank": 3, "cfg": "MCLK/D4", "diff": "N", "pair": "IOR34A"},
  {"n": "L11", "name": "VSS", "type": "gnd"},
  {"n": "L12", "name": "IOT32B", "type": "io", "bank": 1, "diff": "N", "pair": "IOT32A", "lvds": true},
  {"n": "L13", "name": "IOT38B", "type": "io", "bank": 1, "diff": "N", "pair": "IOT38A", "lvds": true},
  {"n": "L14", "name": "IOT34B", "type": "io", "bank": 1, "diff": "N", "pair": "IOT34A", "lvds": true},
  {"n": "L15", "name": "IOT2A", "type": "io", "bank": 0, "diff": "P", "pair": "IOT2B", "lvds": true},
  {"n": "L16", "name": "IOT34A", "type": "io", "bank": 1, "diff": "P", "pair": "IOT34B", "lvds": true},
  {"n": "M1", "name": "IOB30B", "type": "io", "bank": 4, "cfg": "GCLKC_4", "diff": "N", "pair": "IOB30A", "lvds": true},
  {"n": "M2", "name": "IOB43A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB43B"},
  {"n": "M3", "name": "IOB42A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB42B", "lvds": true},
  {"n": "M4", "name": "VCCIO4", "type": "pwr"},
  {"n": "M5", "name": "VSS", "type": "gnd"},
  {"n": "M6", "name": "IOR44A", "type": "io", "bank": 3, "diff": "P", "pair": "IOR44B", "lvds": true},
  {"n": "M7", "name": "IOR47A", "type": "io", "bank": 3, "cfg": "RPLL2_T_FB", "diff": "P", "pair": "IOR47B", "lvds": true},
  {"n": "M8", "name": "IOR36A", "type": "io", "bank": 3, "cfg": "SO/D1", "diff": "P", "pair": "IOR36B"},
  {"n": "M9", "name": "IOR34A", "type": "io", "bank": 3, "cfg": "MCS_N/D5", "diff": "P", "pair": "IOR34B"},
  {"n": "M10", "name": "IOR22A", "type": "io", "bank": 2, "diff": "P", "pair": "IOR22B", "lvds": true},
  {"n": "M11", "name": "IOR27B", "type": "io", "bank": 2, "cfg": "GCLKC_2", "diff": "N", "pair": "IOR27A"},
  {"n": "M12", "name": "VSS", "type": "gnd"},
  {"n": "M13", "name": "VCCIO1", "type": "pwr"},
  {"n": "M14", "name": "IOT40A", "type": "io", "bank": 1, "diff": "P", "pair": "IOT40B", "lvds": true},
  {"n": "M15", "name": "IOT40B", "type": "io", "bank": 1, "diff": "N", "pair": "IOT40A", "lvds": true},
  {"n": "M16", "name": "IOR30A", "type": "io", "bank": 3, "cfg": "MODE0", "diff": "P", "pair": "IOR30B"},
  {"n": "N1", "name": "IOB42B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB42A", "lvds": true},
  {"n": "N2", "name": "IOB41A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB41B"},
  {"n": "N3", "name": "IOB43B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB43A"},
  {"n": "N4", "name": "VSS", "type": "gnd"},
  {"n": "N5", "name": "VCCIO3", "type": "pwr"},
  {"n": "N6", "name": "IOR51A", "type": "io", "bank": 3, "diff": "P", "pair": "IOR51B", "lvds": true},
  {"n": "N7", "name": "IOR47B", "type": "io", "bank": 3, "cfg": "RPLL2_C_FB", "diff": "N", "pair": "IOR47A", "lvds": true},
  {"n": "N8", "name": "IOR40A", "type": "io", "bank": 3, "diff": "P", "pair": "IOR40B", "lvds": true},
  {"n": "N9", "name": "IOR36B", "type": "io", "bank": 3, "cfg": "SSPI_CS_N/D0", "diff": "N", "pair": "IOR36A"},
  {"n": "N10", "name": "IOR27A", "type": "io", "bank": 2, "cfg": "GCLKT_2", "diff": "P", "pair": "IOR27B"},
  {"n": "N11", "name": "IOR22B", "type": "io", "bank": 2, "diff": "N", "pair": "IOR22A", "lvds": true},
  {"n": "N12", "name": "VCCIO2", "type": "pwr"},
  {"n": "N13", "name": "VSS", "type": "gnd"},
  {"n": "N14", "name": "IOT52B", "type": "io", "bank": 1, "diff": "N", "pair": "IOT52A", "lvds": true},
  {"n": "N15", "name": "IOT48A", "type": "io", "bank": 1, "diff": "P", "pair": "IOT48B", "lvds": true},
  {"n": "N16", "name": "IOT52A", "type": "io", "bank": 1, "diff": "P", "pair": "IOT52B", "lvds": true},
  {"n": "P1", "name": "IOB41B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB41A"},
  {"n": "P2", "name": "IOB44B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB44A", "lvds": true},
  {"n": "P3", "name": "VSS", "type": "gnd"},
  {"n": "P4", "name": "IOB45A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB45B"},
  {"n": "P5", "name": "IOB50A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB50B", "lvds": true},
  {"n": "P6", "name": "IOR53A", "type": "io", "bank": 3, "diff": "P", "pair": "IOR53B", "lvds": true},
  {"n": "P7", "name": "IOR49B", "type": "io", "bank": 3, "diff": "N", "pair": "IOR49A", "lvds": true},
  {"n": "P8", "name": "IOR42A", "type": "io", "bank": 3, "diff": "P", "pair": "IOR42B", "lvds": true},
  {"n": "P9", "name": "IOR38B", "type": "io", "bank": 3, "cfg": "DOUT/WE_N", "diff": "N", "pair": "IOR38A", "lvds": true},
  {"n": "P10", "name": "IOR33A", "type": "io", "bank": 3, "cfg": "MI/D7", "diff": "P", "pair": "IOR33B", "lvds": true},
  {"n": "P11", "name": "IOR24B", "type": "io", "bank": 2, "diff": "N", "pair": "IOR24A", "lvds": true},
  {"n": "P12", "name": "IOR8A", "type": "io", "bank": 2, "cfg": "RPLL1_T_FB", "diff": "P", "pair": "IOR8B", "lvds": true},
  {"n": "P13", "name": "IOR11B", "type": "io", "bank": 2, "diff": "N", "pair": "IOR11A", "lvds": true},
  {"n": "P14", "name": "VSS", "type": "gnd"},
  {"n": "P15", "name": "IOT54A", "type": "io", "bank": 1, "diff": "P", "pair": "IOT54B", "lvds": true},
  {"n": "P16", "name": "IOT48B", "type": "io", "bank": 1, "diff": "N", "pair": "IOT48A", "lvds": true},
  {"n": "R1", "name": "IOB44A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB44B", "lvds": true},
  {"n": "R2", "name": "VSS", "type": "gnd"},
  {"n": "R3", "name": "IOB48A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB48B", "lvds": true},
  {"n": "R4", "name": "IOB52A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB52B", "lvds": true},
  {"n": "R5", "name": "IOB50B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB50A", "lvds": true},
  {"n": "R6", "name": "IOB54A", "type": "io", "bank": 4, "diff": "P", "pair": "IOB54B", "lvds": true},
  {"n": "R7", "name": "IOR49A", "type": "io", "bank": 3, "diff": "P", "pair": "IOR49B", "lvds": true},
  {"n": "R8", "name": "IOR29B", "type": "io", "bank": 3, "cfg": "GCLKC_3", "diff": "N", "pair": "IOR29A", "lvds": true},
  {"n": "R9", "name": "IOR35A", "type": "io", "bank": 3, "cfg": "FASTRD_N/D3", "diff": "P", "pair": "IOR35B", "lvds": true},
  {"n": "R10", "name": "IOR33B", "type": "io", "bank": 3, "cfg": "MO/D6", "diff": "N", "pair": "IOR33A", "lvds": true},
  {"n": "R11", "name": "IOR17A", "type": "io", "bank": 2, "diff": "P", "pair": "IOR17B", "lvds": true},
  {"n": "R12", "name": "IOR11A", "type": "io", "bank": 2, "diff": "P", "pair": "IOR11B", "lvds": true},
  {"n": "R13", "name": "IOR20A", "type": "io", "bank": 2, "diff": "P", "pair": "IOR20B", "lvds": true},
  {"n": "R14", "name": "IOR7B", "type": "io", "bank": 2, "cfg": "RPLL1_C_IN", "diff": "N", "pair": "IOR7A"},
  {"n": "R15", "name": "VSS", "type": "gnd"},
  {"n": "R16", "name": "IOT54B", "type": "io", "bank": 1, "diff": "N", "pair": "IOT54A", "lvds": true},
  {"n": "T1", "name": "VCC", "type": "pwr"},
  {"n": "T2", "name": "IOB48B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB48A", "lvds": true},
  {"n": "T3", "name": "IOB52B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB52A", "lvds": true},
  {"n": "T4", "name": "IOB45B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB45A"},
  {"n": "T5", "name": "IOB54B", "type": "io", "bank": 4, "diff": "N", "pair": "IOB54A", "lvds": true},
  {"n": "T6", "name": "IOR53B", "type": "io", "bank": 3, "diff": "N", "pair": "IOR53A", "lvds": true},
  {"n": "T7", "name": "IOR29A", "type": "io", "bank": 3, "cfg": "GCLKT_3", "diff": "P", "pair": "IOR29B", "lvds": true},
  {"n": "T8", "name": "IOR42B", "type": "io", "bank": 3, "diff": "N", "pair": "IOR42A", "lvds": true},
  {"n": "T9", "name": "IOR38A", "type": "io", "bank": 3, "cfg": "DIN/CLKHOLD_N", "diff": "P", "pair": "IOR38B", "lvds": true},
  {"n": "T10", "name": "IOR35B", "type": "io", "bank": 3, "cfg": "SI/D2", "diff": "N", "pair": "IOR35A", "lvds": true},
  {"n": "T11", "name": "IOR24A", "type": "io", "bank": 2, "diff": "P", "pair": "IOR24B", "lvds": true},
  {"n": "T12", "name": "IOR17B", "type": "io", "bank": 2, "diff": "N", "pair": "IOR17A", "lvds": true},
  {"n": "T13", "name": "IOR8B", "type": "io", "bank": 2, "cfg": "RPLL1_C_FB", "diff": "N", "pair": "IOR8A", "lvds": true},
  {"n": "T14", "name": "IOR20B", "type": "io", "bank": 2, "diff": "N", "pair": "IOR20A", "lvds": true},
  {"n": "T15", "name": "IOR7A", "type": "io", "bank": 2, "cfg": "RPLL1_T_IN", "diff": "P", "pair": "IOR7B"},
  {"n": "T16", "name": "VCC", "type": "pwr"}
]}
};
